version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: dockerize -wait tcp://db:5432 python manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - 8005:8000
    depends_on:
      - db
    volumes:
      - .:/app/

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: billing_project
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    restart: always
